function frDemoNar() {
	frHTML += "<a href = '#frdemonar' class='buttonlink color1'>Read Narrative</a>";
	frHTML += '<div id="frdemonar" class="overlay">';
	frHTML += '<div class="popup">';
	frHTML += '<h2>Freshmen Demographics</h2>';
	frHTML += '<h3>By Shaina Peters</h3>'
	frHTML += '<a class="close color1" href="#close">×</a>';
	frHTML += '<div class="content">';
	frHTML += 'Introducing the incoming Class of 2020. Divided closely down the middle in terms of gender, the freshman class has slightly more boys (51.3 percent) than girls (47.8 percent) and very few people identifying as other. While boys still outnumber girls, the gap has narrowed since last year, when boys represented 53.6 percent of the freshman class and girls represented 44.9 percent.';
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += "Race is far less representative of the New York City population. While blacks and Hispanics represent 67.6 percent of students in the New York City Public Schools system, together make up only 1.6 percent of the freshman respondents. At Stuyvesant, Asian students make up 75.3 percent of the incoming class, and white students represent 17.5 percent of the population. Of the incoming freshmen, a vast majority of students (86.4 percent) are U.S. citizens.";
	//frHTML += 'Race is far less representative of the New York City population. While blacks and Hispanics together make up only 1.6 percent of the total population, they represent 67.6 percent of students in the New York City Public Schools system. At Stuyvesant, Asian students make up 75.3 percent of the incoming class, and white students represent 17.5 percent of the population. Of the incoming freshmen, a vast majority of students (86.4 percent) are U.S. citizens.';
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += 'Stuyvesant students are very diverse in terms of religion, representing Christianity, Islam, and Judaism, with a significant number (24.5 percent) practicing other faiths, likely Buddhism or Hinduism. The most common response, however, was atheism or agnosticism, which a little over a third of the incoming class marked as the religion with which they most identify.';
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += 'Nearly 70 percent of the students surveyed identified as middle or upper middle class, with relatively few falling on the ends of the spectrum. It should be noted, however, that freshmen may not be fully aware of their actual socioeconomic status; indeed, 20 percent responded that they didn’t know. Among those who identified themselves as upper class or upper middle class, most were white.';
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += 'Almost three-quarters of the class has parents with college or post-college education, but what is perhaps more striking is that a quarter of the class will soon surpass or has already surpassed their parents in terms of education.';
	frHTML += "<br><br>";
	frHTML += 'When it comes to sexual orientation, most students (86.7 percent) identified as straight. And at this point in their lives, 6.5 percent are still unsure.';
	frHTML += '<br><br>';
	frHTML += 'Citywide data taken from schools.nyc.gov';
	frHTML += '</div></div></div>';
	frHTML += "<hr class='sep'>";
}
function frAppNar() {
	frHTML += "<a href = '#frappnar' class='buttonlink color2'>Read Narrative</a>";
	frHTML += '<div id="frappnar" class="overlay">';
	frHTML += '<div class="popup">';
	frHTML += '<h2>Applying to Stuyvesant</h2>';
	frHTML += '<h3>By Anne George</h3>';
	frHTML += '<a class="close color2" href="#close">×</a>';
	frHTML += '<div class="content">';
	frHTML += "More than half of the freshmen attended selective public schools, while 39.6 percent attended zoned public schools. Only 4.5 percent of students went to private school, while even fewer students went to parochial school. Home-schooled students formed a minority at 0.1 percent.";
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += "The majority of students who attended a selective public school were white (64.3 percent), while the majority of students who attended zoned public schools or parochial schools were Asian.";
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += "While most students (27.9 percent) studied for the SHSAT six months to a year before the exam, a surprising 21.2 percent of students studied for over a year. Only 4.1 percent of students did not study.";
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += "The majority of students who studied for over a year were Asian, while the majority of students who did not study were white. The students who prepared for the most time were largely from lower socioeconomic backgrounds, while the students who prepared for the least amount of time were largely from upper middle class backgrounds, possibly because they had the option of going to prestigious private schools.";
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += "The incoming class largely utilized preparatory classes to study for the SHSAT. Most of the students who went to preparatory classes, including the SHSI program, were Asian. Additionally, 14.5 percent of students self-studied. Students who prepared for the largest amount of time studied through preparatory classes, while students who prepared for the least amount of time self-studied.";
	frHTML += "<br><br>";
	frHTML += "A prominent 51.4 percent of freshmen said that parental pressure played some sort of a role in their decision to attend Stuyvesant. Relatively few students had no say in the decision to attend Stuyvesant, but of these students, the majority have parents whose highest level of education is high school. Of the students who made the decision to attend Stuyvesant by themselves, the majority were black, Hispanic, or other. For upper middle class students, parental pressure did not play as significant of a role as it did for middle class and lower class students.";
	frHTML += '</div></div></div>';
	frHTML += "<hr class='sep'>";
}
function frMidacNar() {
	frHTML += "<a href = '#frmidacnar' class='buttonlink color3'>Read Narrative</a>";
	frHTML += '<div id="frmidacnar" class="overlay">';
	frHTML += '<div class="popup">';
	frHTML += '<h2>Middle School Acedemics</h2>';
	frHTML += '<h3>By Sonia Epstein</h3>';
	frHTML += '<a class="close color3" href="#close">×</a>';
	frHTML += '<div class="content">';
	frHTML += "Freshman responses to hours spent on homework per night during middle school fall in a normal distribution, with the mode (36.5 percent of the respondents) at one to two hours, and the extremes at less than half an hour or more than three hours.";
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += "Our results show that time spent on homework is largely independent of race or type of middle school, but is correlated with gender, with 41.6 percent of females spending over two hours on homework a night, while only half as many males reported the same.";
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += "These responses are in line with freshman responses to the statement “I have a strong work ethic”: while much of the class (68.4 percent) agreed or strongly agreed, females were more likely to do so.";
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += "Females were also more likely to sleep fewer hours a night, a possible outcome of spending more time on homework. Nearly half of all females reported getting less than 7 hours of sleep in middle school, compared to the roughly 30 percent of males who answered the same.";
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += "The most popular subjects this year were math and science, which gained 41.3 and 26.6 percent of votes, respectively. This is a reversal of last year, where 45.1 percent of the class favored science and 24.9 percent of the class favored math.";
	frHTML += "<br><br>";
	frHTML += "Less than 10 percent of the respondents prefer English class, with a majority of them being female or white.  STEM subjects were, overall, more popular among males.";
	frHTML += "<br><br>";
	frHTML += "In general, the incoming class is filled with eager students. Nearly three-quarters of the respondents agreed that they are active participants in class (with boys and white students more likely to do so) and outside of the classroom, the students are no less inquisitive; over half replied that they consider themselves aware of current events.";
	frHTML += '</div></div></div>';
	frHTML += "<hr class='sep'>";
}
function frMidlifeNar() {
	frHTML += "<a href = '#frmidlifenar' class='buttonlink color4'>Read Narrative</a>";
	frHTML += '<div id="frmidlifenar" class="overlay">';
	frHTML += '<div class="popup">';
	frHTML += '<h2>Middle School Life and Identity</h2>';
	frHTML += "<h3>By Sophie Watwood</h3>";
	frHTML += '<a class="close color4" href="#close">×</a>';
	frHTML += '<div class="content">';
	frHTML += "<br><br>";
	frHTML += "The class of 2020 is both social and innocent. 67.6 percent of freshmen self-reported as sociable. Students identifying as white disproportionately perceived themselves as social, comprising more than half of the “strongly agrees.” People of color skewed towards the neutral category. This upholds common stereotypes that white people tend to be less reserved.";
	frHTML += "<br><br>";
	frHTML += "Females were more likely than males to watch more than three or even seven hours of television a week. Males were more likely to watch less than three. Predictably, the students who watched more than seven hours of television a week often got fewer than six hours of sleep.";
	frHTML += "<br><br>";
	frHTML += "Similarly, those who spent more than three hours a week on Facebook often got less than six hours of sleep a night, and those who didn’t spend time on Facebook, but got fewer than six hours of sleep, usually reported having some other form of social media. Furthermore, a full 43.4 percent of incoming freshman didn’t even have Facebook, and those who did usually spend less than one and a half hours on it a week.Similarly, those who spent more than three hours a week on Facebook often got less than six hours of sleep a night, and those who didn’t spend time on Facebook, but got fewer than six hours of sleep, usually reported having some other form of social media. Furthermore, a full 43.4 percent of incoming freshman didn’t even have Facebook, and those who did usually spend less than one and a half hours on it a week.";
	frHTML += "<br><br>";
	frHTML += "Asian students spent the most time on Facebook, comprising everyone who spent more than three hours on  Facebook a week. 72.2 percent of white students didn’t have Facebook, suggesting a stark cultural difference.";
	frHTML += "<br><br>";
	frHTML += "65.3 percent of students said that they were opposed to the use of recreational drugs in high school. Asians were most strongly opposed, while white students were the least opposed. Christians were also more radically opposed than any other group.";
	frHTML += "<br><br>";
	frHTML += "Interestingly, more than half of the freshmen partook in academic dishonesty at some point in their middle school careers, but luckily, 73.7 percent said that they would rather sacrifice a good grade than cheat.";
	frHTML += '</div></div></div>';
	frHTML += "<hr class='sep'>";
}
function frExNar() {
	frHTML += "<a href = '#frexnar' class='buttonlink color5'>Read Narrative</a>";
	frHTML += '<div id="frexnar" class="overlay">';
	frHTML += '<div class="popup">';
	frHTML += '<h2>Expectations of Stuyvesant and Future Plans</h2>';
	frHTML += "<h3>By Liam Elkind</h3>";
	frHTML += '<a class="close color5" href="#close">×</a>';
	frHTML += '<div class="content">';
	frHTML += "The results of this portion of the survey largely reflect the incoming class of 2020’s optimism for their upcoming years at Stuyvesant, with over half the surveyed population noting that they feel prepared for the academics at Stuyvesant.";
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += "In breaking down these results, we found that males and selective public school students were slightly more likely to say they felt prepared for Stuyvesant than females and zoned public school students were.";
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += "Notably, of those who made the decision to come to Stuyvesant themselves, free from parental pressure, about two-thirds reported that they were confident for Stuyvesant’s academics. On the flipside, only 38.1 percent of the students whose parents had made the decision for them felt ready for Stuyvesant.";
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += "When asked how they thought they would stack up against the rest of the class academically, the students were charming idealists: 95.1 percent of the grade believes that they will be in the top 50 percent of the class.";
	frHTML += "<br>"; frHTML += "<br>";
	frHTML += "Again, males expressed more confidence than females in this field, with almost 75 percent of men expecting a top 25 percent rank, whereas only 61.6 percent of women expected the same. Additionally, white students were slightly more confident than those of other races, with 80 percent of white students expecting a class rank in the top quarter.";
	frHTML += "<br><br>";
	frHTML += "The students’ expectations for how much sleep they will get were more realistic, almost saddeningly so: students expected under six hours, with 5-6 hours as the most common choice at 39.9 percent. For reference, only 7.2 percent of students got fewer than six hours of sleep in middle school, with a quarter getting over eight hours. Fewer than two percent of students expected to get more than eight hours of sleep, even though the National Sleep Foundation recommends eight to ten hours of sleep nightly for teens.";
	frHTML += "<br><br>";
	frHTML += "Males typically expected more sleep than females, and other races typically expected more sleep than incoming Asian students, with a majority of Asian students (64.2 percent) expecting fewer than six hours of sleep per night.";
	frHTML += "<br><br>";
	frHTML += "Interestingly, those who expected to perform more poorly in school (in the bottom half of the class) were much more likely to expect less sleep, with 46.9% expecting fewer than five hours.";
	frHTML += "<br><br>";
	frHTML += "We asked incoming students if they expected to attend an Ivy League University, MIT, or Stanford when they graduated from Stuyvesant. 65.3 percent of students agreed or strongly agreed that they might. For reference, 17.4 percent of the graduating seniors we surveyed are attending an Ivy League University this coming school year, through Naviance data shows that this number is closer to 10 to 15 percent.";
	frHTML += "<br><br>";
	frHTML += "White students and those coming from upper-class families were much more likely to expect a college education at one of these schools, with a remarkable 85.7 percent of upper class students anticipating an elite college. Students with parents who had a post-college education were also more likely to expect attendance at one of these schools.";
	frHTML += "<br><br>";
	frHTML += "Incoming first-year students also responded to what extracurricular activity they would be most likely to participate in. While the five main categories (academic clubs/publications, debate/government, community service, sports, and the arts) each had fair representation, sports was the most popular activity at 29.5 percent, and community service was the least popular at 7.4 percent.";
	frHTML += "<br><br>";
	frHTML += "These results affirmed popular stereotypes, with males taking a much greater interest in sports than females, and females taking more interest in the arts than males. Other activities had equal interest from both sexes.";
	frHTML += "<br><br>";
	frHTML += "White students reported a higher likelihood of participating in sports than other students, with 45.0 percent saying it would be their first choice of an extracurricular. Asian students, on the other hand, were most likely to choose an academic club or publication.";
	frHTML += "<br><br>";
	frHTML += "In line with Stuyvesant’s reputation as a math and science school, 59.6 percent of students want to go into a STEM-related field. The next largest group, 22.2 percent of the incoming class, said they were unsure or had a choice other than those provided. Of the small remaining pool, 8.7 percent want to pursue finance, business, or management and 8.5 percent are interested in social studies.";
	frHTML += "<br><br>";
	frHTML += "Only 1.7 percent of students wish to pursue English language studies, making STEM fields 35 times more popular than English.";
	frHTML += "<br><br>";
	frHTML += "Males were notably more likely than females to want to go into a STEM-related field, with 67.7 percent of males selecting this choice, as opposed to 51.5 percent of females. By contrast, 10.7 percent of females want to go into a social science field, whereas only 2.9 percent of males do. There was no notable racial disparity in career ambition.";
	frHTML += '</div></div></div>';
	frHTML += "<hr class='sep'>";
}

function srDemoNar() {
	srHTML += "<a href = '#srdemonar' class='buttonlink color1'>Read Narrative</a>";
	srHTML += '<div id="srdemonar" class="overlay">';
	srHTML += '<div class="popup">';
	srHTML += '<h2>Senior Demographics</h2>';
	srHTML += "<h3>By Sonia Epstein</h3>";
	srHTML += '<a class="close color1" href="#close">×</a>';
	srHTML += '<div class="content">';
	srHTML += "In conducting the Senior Survey, we did not have the luxury of being able to gather the whole Class of 2016 together, as we did with the incoming Class of 2020 Freshman Survey.";
	//srHTML += "In conducting the Senior Survey, we did not have the luxury of being able to gather the whole senior class together, as we did with the Freshman Survey.";
	srHTML += "<br>"; srHTML += "<br>";
	srHTML += "The 161 students who did respond to the survey are split rather evenly between males (49.7 percent) and females (47.8 percent), with more students identifying outside the gender binary than we found in the freshman survey (2.5 percent versus 0.9 percent). This could be a result of our sample size, or a reflection of shifting gender identities among high school students.";
	srHTML += "<br>"; srHTML += "<br>";
	srHTML += "Racially, our results were an approximate reflection of a typical Stuyvesant class, but skewed more toward white students (26.1 percent of the responses), with a smaller proportion of Asian students (60.2 percent), few Hispanics (1.2 percent) and no black students.";
	srHTML += "<br>"; srHTML += "<br>";
	srHTML += "Because we conducted the Senior Survey online, we were able to add more than five answer choices (the limit on the Scantrons used for the Freshman Survey). This allowed us to break down the large group of students blanketed under the term “Asian” into students of East and South Asian backgrounds (44.7 and 15.5 percent, respectively).";
	srHTML += "<br>"; srHTML += "<br>";
	srHTML += "Additionally, 12.4 percent of our respondents were multiracial.";
	srHTML += "<br><br>";
	srHTML += "Those surveyed also represented the religious diversity of the class, though they were perhaps disproportionately Jewish (12.4 percent versus 5.4 percent of the freshman surveyed). Five percent identify as Buddhist and 3.7 percent identify as Hindu, statistics we don’t have from the Freshman Survey, where students of these religions are lumped into the “Other” category.";
	srHTML += "<br><br>";
	srHTML += "Of those surveyed, 82.6 percent identify as heterosexual, and 12.4 reported that their perceived sexual orientation changed over high school (5 percent were unsure if it had).";
	srHTML += "<br><br>";
	srHTML += "Most students (86.3 percent) came from public schools, with 8.7 percent coming from private schools.";
	srHTML += "<br><br>";
	srHTML += "A vast majority of those surveyed (80.1 percent) identified their socioeconomic status as somewhere on the spectrum of middle class. Students at the other ends of the spectrum, from lower or working class and upper class families, comprised about 13 and five percent of those surveyed, respectively.";
	srHTML += "<br><br>";
	srHTML += "The most notable difference between freshman and senior responses to this question was that by senior year, only 1.9 percent of students responded that they were unaware of their socioeconomic background—with freshmen, that number was 20 percent.";
	srHTML += '</div></div></div>';
	srHTML += "<hr class='sep'>";
}
function srAcNar() {
	srHTML += "<a href = '#sracnar' class='buttonlink color2'>Read Narrative</a>";
	srHTML += '<div id="sracnar" class="overlay">';
	srHTML += '<div class="popup">';
	srHTML += '<h2>Stuyvesant Acedemics Narrative</h2>';
	srHTML += "<h3>By Danielle Eisenman</h3>";
	srHTML += '<a class="close color2" href="#close">×</a>';
	srHTML += '<div class="content">';
	srHTML += "Almost 90 percent of the graduated seniors who took this survey had GPAs over 90. The GPAs were heavily concentrated between 85 and 97. A mere 4 percent of students had averages below 85, and even less—2.5 percent—had averages at the other end of the spectrum, above 97.";
	srHTML += "<br>"; srHTML += "<br>";
	srHTML += "Perhaps the rarity of college applicants with averages above 97 is what makes them so impressive to Ivy League schools, which are among the most elite colleges. The fact that 75 percent of the respondents attending Ivy League schools have GPAs above 97 goes to show that having the highest grades really does matter.";
	srHTML += "<br>"; srHTML += "<br>";
	srHTML += "Other top ten schools like Stanford, MIT, and the University of Chicago are just as selective (if not more) than the Ivies. However, the respondents attending these schools are more likely to have slightly lower averages (between 95 and 97).";
	srHTML += "<br>"; srHTML += "<br>";
	srHTML += "The schools that are most popular with Stuyvesant students—SUNYs and CUNYs—are the most popular with respondents whose GPAs hover around the schoolwide average (between 85 and 89). Of the students who filled out our survey, zero students with GPAs above 97 are attending SUNYs.";
	srHTML += "<br>"; srHTML += "<br>";
	srHTML += "The schools that are most popular with Stuyvesant students—SUNYs and CUNYs—are the most popular with respondents whose GPAs hover around the schoolwide average (between 85 and 89). Of the students who filled out our survey, zero students with GPAs above 97 are attending SUNYs.";
	srHTML += "<br><br>";
	srHTML += "Just over half of the respondents attending SUNYs and CUNYs consider themselves lower-middle class, which makes sense, given the affordability of in-state tuition.";
	srHTML += "<br><br>";
	srHTML += "However, class was not a barrier: more than a quarter of students attending Ivy League schools consider themselves to be lower or working class. This can probably be attributed to the popularity of scholarship programs for low-income students, like Questbridge, and the abilities Ivy League schools have to “meet 100 percent of demonstrated financial need” with their financial aid.";
	srHTML += "<br><br>";
	srHTML += "In addition, the fact that so many low-income students are attending Ivy League schools goes against the stereotype that everyone at these schools is extremely privileged. However, it may also be because 43 percent of Stuyvesant students receive free lunch (and even more receive reduced lunch), meaning that many members of the student body come from low-income households.";
	srHTML += "<br><br>";
	srHTML += "The graduated seniors are currently figuring out what they will be studying in college, and just over half of them said that their academic focuses changed during their time at Stuyvesant. While the nature of being a teenager encourages change, so do inspiring teachers. The common wisdom at Stuyvesant is that there are definitely bad teachers, a good amount of average ones, and a couple really amazing ones. Most students said they had either two or three teachers who strongly impacted them.";
	srHTML += '</div></div></div>';
	srHTML += "<hr class='sep'>";
}
function srLifeNar() {
	srHTML += "<a href = '#srlifenar' class='buttonlink color3'>Read Narrative</a>";
	srHTML += '<div id="srlifenar" class="overlay">';
	srHTML += '<div class="popup">';
	srHTML += '<h2>Student Life and Identity</h2>';
	srHTML += "<h3>By Blythe Zadrozny</h3>";
	srHTML += '<a class="close color3" href="#close">×</a>';
	srHTML += '<div class="content">';
	srHTML += "Students didn’t seem to get much sleep. Most health organizations recommend that teenagers sleep for at least nine hours a night, but only 1.2 percent of respondents slept more than eight hours a night as upperclassmen.";
	srHTML += "<br>"; srHTML += "<br>";
	srHTML += "The lack of sleep could contribute to lower GPAs, since zero respondents with GPAs below 85 slept for more than 6 hours a night, while many with GPAs over 90 did.";
	srHTML += "<br>"; srHTML += "<br>";
	srHTML += "Whether or not students partook in academic dishonesty also seemed to affect their GPAs. Zero students with GPAs over 95 saw frequently partook in academic dishonesty, while the majority of students with GPAs below 89 partook in academic dishonesty at least frequently. Although it is worrisome that only a minority of students never committed academic dishonesty, things like cheating and copying homework are common occurrences in many high schools where the stakes and stress levels are as high as they are at Stuyvesant.";
	srHTML += "<br>"; srHTML += "<br>";
	srHTML += "Stuyvesant’s focus on grades and academic success was especially apparent when students were asked about how often they partook in illicit activities. A substantial majority of students leaving Stuyvesant never partook in sexual activity or the use of substances such as marijuana, prescription or study drugs. The exception as alcohol, as 42.1 percent of students had at least tried it.";
	srHTML += "<br>"; srHTML += "<br>";
	srHTML += "The vast majority of graduated seniors surveyed ultimately were glad to have attended Stuyvesant. Although the specific numbers changed based on GPA, college enrolled in, and number of inspirational teachers, no variation saw a majority of students who thought they should not have attended Stuyvesant.";
	srHTML += '</div></div></div>';
	srHTML += "<hr class='sep'>";
}

function compNar() {
	compHTML += "<a href = '#compnar' class='buttonlink color1'>Read Narrative</a>";
	compHTML += '<div id="compnar" class="overlay">';
	compHTML += '<div class="popup">';
	compHTML += '<h2>Freshmen vs. Seniors: How Different Were They, Really?</h2>';
	compHTML += "<h3>By Julia Ingram</h3>";
	compHTML += '<a class="close color1" href="#close">×</a>';
	compHTML += '<div class="content">';
	compHTML += "Among the most significant differences between the incoming freshmen and graduating seniors’ responses were with regard to religion. The percent of students identifying as agnostic or atheist increased from 34.5 percent to 51.6 percent, perhaps an indication that many students abandon their family’s religion as they go through high school.";
	//compHTML += 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut lacinia risus. Sed volutpat sem ac nunc condimentum, efficitur volutpat erat accumsan. Integer vestibulum congue leo, sed hendrerit risus aliquet posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu laoreet dui. Nam cursus orci pharetra erat lacinia, finibus lacinia dolor elementum. Cras eleifend magna non dapibus dapibus. Nullam consequat venenatis arcu, eget finibus eros bibendum ut.\n';
	compHTML += "<br>"; compHTML += "<br>";
	compHTML += "Answers to the academics-related questions also differed drastically. While a combined 65.3 percent of incoming freshmen agree or strongly agree that they will attend an elite university, only 35.4 percent of seniors polled will actually attend these top colleges. Naviance data shows that this percentage is even smaller.";
	//compHTML += "Answers to the academics-related questions also differed drastically. While a combined 65.3 percent of incoming freshmen agree or strongly agree that they will attend an Ivy League University, Stanford University, or MIT, only 35.4 percent of seniors polled will actually attend such colleges. Naviance data shows that this percentage is smaller.";
	//compHTML += 'Vestibulum laoreet mauris quis leo bibendum, in semper metus imperdiet. Duis malesuada accumsan lorem, eget pretium felis. Praesent eu sem sagittis, facilisis tortor quis, semper arcu. Vivamus in porttitor ligula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas sagittis elit rutrum, vestibulum nibh volutpat, feugiat est. Suspendisse id mauris a risus elementum mattis et a eros. Sed lacinia tellus urna, eget posuere nunc vehicula at. Etiam efficitur vitae ante id sagittis. Quisque sodales vitae velit vel posuere. Duis egestas ultricies lectus, id dapibus sem lobortis quis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc neque est, suscipit quis iaculis sed, porta a enim. Suspendisse porta nunc orci, sed tempor massa lobortis id. Integer ornare ante facilisis, porttitor lectus ac, porta felis.\n';
	compHTML += "<br>"; frHTML += "<br>";
	compHTML += "Additionally, the percent of freshmen who agreed that their middle school prepared them for Stuyvesant was nearly double that of the seniors. This is to be expected—freshmen often have unrealistically optimistic expectations for Stuyvesant, with 95.2 percent of the Class of 2020 anticipating they would be within the top half of their class.";
	//compHTML += 'Etiam in ex leo. Maecenas eget consequat orci. Duis quis orci a velit euismod pharetra eget vitae ante. Nam sit amet ultrices felis. Proin ut ligula felis. Maecenas sit amet sapien mollis ipsum dapibus fermentum. Integer maximus leo dignissim, euismod elit vel, luctus elit. Mauris faucibus porttitor velit a aliquam.\n';
	compHTML += "<br>"; compHTML += "<br>";
	compHTML += "A comparison of the amount of sleep middle schoolers versus high schoolers seemed to follow the stereotype of the sleep-deprived Stuyvesant student. While 42.1 percent of the seniors recorded they got between five and six hours of sleep as upperclassmen (30 percent got the same amount as underclassmen) only 7.2 percent of the freshmen answered they slept less than six hours per night in middle school. Instead, the vast majority of freshmen—nearly 70 percent—got between 6 and 8 hours of sleep in middle school.";
	//compHTML += 'Aliquam fringilla molestie lorem sed auctor. Suspendisse in diam varius, suscipit augue hendrerit, rhoncus mauris. Mauris gravida ullamcorper neque id auctor. Phasellus sed nibh massa. Etiam non sem vestibulum, fringilla odio id, vulputate eros. Cras ultricies metus in leo fringilla, et cursus lorem congue. Nam volutpat semper hendrerit. Cras vitae tortor ut mauris faucibus eleifend quis id libero. Nunc euismod eros suscipit molestie mattis. Donec gravida, eros nec aliquam porttitor, nulla eros posuere urna, at eleifend metus massa ac leo.\n';
	compHTML += "<br>"; compHTML += "<br>";
	compHTML += "However, responses to questions about illicit behavior were strikingly similar to that of the seniors: 64.9 percent of freshmen strongly agreed that they are opposed to the use of alcohol by high school students, while 57.1 percent of seniors answered they had never drank alcohol, and 65.3 strongly agreed to the same statement about recreational drugs, with an even larger 81.3 percent of seniors having never done drugs.";
	//compHTML += 'Nullam bibendum aliquam arcu, a suscipit tortor mollis id. Nulla gravida, nunc id scelerisque pulvinar, augue enim consequat lectus, sit amet laoreet nisi mi ac velit. Etiam lacinia turpis orci, a tincidunt est commodo a. Fusce laoreet mauris ac vulputate volutpat. Proin ut tincidunt dolor, lacinia malesuada augue. Vestibulum et interdum tortor. Donec laoreet sapien non lacus viverra, vitae imperdiet turpis maximus. Nunc efficitur nibh tincidunt erat tincidunt suscipit ut nec nisi. In urna lectus, semper sit amet sem a, blandit maximus magna. Integer vel leo pellentesque, lobortis felis sit amet, consequat ex. Aenean finibus egestas metus. Etiam non tortor eleifend, congue metus nec, eleifend ex. Donec tellus nisi, auctor convallis ipsum in, finibus pretium elit. Aliquam vitae tellus dui. Quisque dictum feugiat nulla.';
	compHTML += "<br><br>";
	compHTML += "On the other hand, the amount of freshmen who never partook in academic dishonesty during middle school—nearly half—is comparable to the number of seniors who said they “rarely” cheated during high school. Only 28.8 percent of seniors never partook in academic dishonesty while at Stuyvesant.";
	compHTML += '</div></div></div>';
	compHTML += "<hr class='sep'>";
}
